version: "3.2"
services:
  zookeeper:
    image: debezium/zookeeper:2.5.2.Final
    container_name: zookeeper
    hostname: zookeeper
    #restart: always
    environment:
      ZOOKEEPER_SERVER_ID: 1
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka:
    image: debezium/kafka:2.5.2.Final
    container_name: kafka
    hostname: kafka
    #restart: always
    ports:
      - "9092:9092"
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      BROKER_ID: 1
      KAFKA_LISTENERS: LISTENER_INNER://kafka:29092,LISTENER_OUTER://:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INNER://kafka:29092,LISTENER_OUTER://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INNER:PLAINTEXT,LISTENER_OUTER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INNER
      KAFKA_ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    depends_on:
      - zookeeper
